### ISSUE TITLE
Random resizing

### ISSUE THREAD

**Issue by piotrekkaminski** [mage2tv/issues#1]
![ezgif-5-5541e2006c](https://user-images.githubusercontent.com/1714545/34847375-b8d78786-f6e0-11e7-8864-c601a291ee77.gif)
(the blue rectangle is just covering my password manager) - on my desktop the screen just jumps between mobile? and desktop view depending on mouse position and clicked link, very distracting.

**Comment by Vinai** [comment]
Wow, very strange! Can you please give me a bit more information about the resolution you are using? And it looks like Chrome, is that correct?

**Comment by piotrekkaminski** [comment]
Chrome latest, Mac, screen res: 2560 x 1440, windows size - not sure how to find out, slightly less then full width

**Comment by Vinai** [comment]
Thanks, should be close enough. I'll see how I can reproduce that!

**Comment by Vinai** [comment]
If you resize the window and make it smaller, does the jumping stop?

**Comment by piotrekkaminski** [comment]
No, same thing

**Comment by Vinai** [comment]
Failing trying to reproduce that. Will ask someone, could well be she can help, she is wise in such things, but probably will be tomorrow. Will keep you posted.

**Comment by Vinai** [comment]
@piotrekkaminski We are so far unable to reproduce the issue :(
However, would you be willing to run a few tests by adding some CSS via the Chrome console?
If so, I'll send you a DM on slack. That would be really great!

**Comment by Vinai** [comment]
What password manager are you using?

**Comment by piotrekkaminski** [comment]
i'm using Dashlane. No problem with adding CSS. i cannot reproduce without password manager, so i guess it's not a big deal.

**Comment by Vinai** [comment]
Confirmed: the following code fixes the login page issue:

```
main.login-page {
    width: 100vw;
}
```

**Comment by Vinai** [comment]
Fix commited and deployed.
If the issue still exists or still happens on different pages, please reopen this issue - thanks!
