### ISSUE TITLE
Add autoplay feature

### ISSUE THREAD

**Issue by jahvi** [mage2tv/issues#11]
Great work @Vinai as always very high quality content, my only feedback is that it would be nice to have some sort of autoplay feature on the videos so the next one plays automatically, I think it would be useful specially since most videos are relatively short.

**Comment by Vinai** [comment]
Thanks @jahvi, good idea!
I would like to make that optional, so some kind of preference or setting.
Would that work for you?

**Comment by jahvi** [comment]
That would be ideal, maybe something like what egghead.io does?

Thanks!

**Comment by Vinai** [comment]
I'm not familiar what egghead.io does to be honest :)
I was thinking maybe of a switch underneath the videos for logged in visitors where they could toggle their autoplay preference right there.

**Comment by jahvi** [comment]
Pretty much that 🙂

![screenshot--2018-01-15-11-58-57-947](https://user-images.githubusercontent.com/661330/34941432-9233134e-f9eb-11e7-8ab7-e08f8254c4b4.png)

**Comment by Vinai** [comment]
@jahvi Follow up question:
Given the autoplay option is enabled, when a video reaches it's end, would you want (or expect) the next video to be played automatically, too?
Edit: just re-read your original issue, question answered.

**Comment by Vinai** [comment]
I'm deploying the feature now. The option to enable/disable the autoplay is a link below each video currently. It still needs to be styled as a toggle-switch, but I decided to push it out so I can get feedback on it.

**Comment by Vinai** [comment]
Leaving this issue open until the toggle switch is styled.

**Comment by jahvi** [comment]
> Given the autoplay option is enabled, when a video reaches it's end, would you want (or expect) the next video to be played automatically, too?

I'd say yes, thanks for your work on this 🙂

**Comment by Vinai** [comment]
Styled and deployed.
