### ISSUE TITLE
Unexpected Accordion Menu Close 

### ISSUE THREAD

**Issue by tjgamble** [mage2tv/issues#12]
On nested accordions, if you click just beside the arrow on the secondary accordion, it closes the primary accordion.    If you click directly on the arrow of the secondary accordion, it opens as expected.   

- Page:  https://www.mage2.tv/content/
- Browser: Chrome Version 63.0.3239.132 (Official Build) (64-bit)
- Hardware: MacBook Pro (Retina, 15-inch, Mid 2015)
- OS:  MacOs High Sierra 10.13.2

See attached animated gif for example.
![2018-01-16 08-15-43_2](https://user-images.githubusercontent.com/1413906/34995964-c09be05a-fa9d-11e7-8aac-b97f5079cd88.gif)

**Comment by Vinai** [comment]
Thank you for such a well crafted issue!
Good catch!

**Comment by tjgamble** [comment]
Glad I could provide just a little assistance.  I'm excited to see what all you do with mage2.tv.  Based on this small contribution, I will always claim full credit for it's inevitable success.

**Comment by Vinai** [comment]
Fixed and deployed.
