### ISSUE TITLE
Popup shows Forbidden 403 Error

### ISSUE THREAD

**Issue by jignesh26** [mage2tv/issues#17]
Hello Vinai,

When I logged on the website. I am seeing one pop up with Forbidden 403 error. 
I have uploaded a screenshot of this error.
![screenshot from 2018-02-20 12-07-04](https://user-images.githubusercontent.com/21121564/36410396-d1e4b8a0-1636-11e8-8ad0-134bc1bfec58.png)

**Comment by jignesh26** [comment]
When I checked the console for the javascript log.

I found the more information is below.

Failed to load resource: the server responded with a status of 403 (Forbidden) => /auth/login

**Comment by Vinai** [comment]
Thanks, I'll check what is going on. Can you please DM me on [twitter](https://twitter.com/vinaikopp) or email me the email address you used to register?

**Comment by Vinai** [comment]
Sorry for the delay checking.
From what I can see you managed to log in and view videos.
Did you log in on two different devices or browsers? If so, the first login is invalidated. Only a single session is possible at one time. Maybe that caused the issue?
Otherwise, does the issue still happen, or is it gone?

**Comment by jignesh26** [comment]
Hello Vinai,

 I have checked the website. The issue is resolved. No, i haven't open account on 2 different devices or web browser. I was able to check the videos earlier. then I move to the main screen of mage2tv. I was logged in but I was seeing the email login link. so I do it again (usually you will get redirect content ) and i was seeing that error. 

Anyway, the issue is resolved. :)
