### ISSUE TITLE
Allow hiding the leftnav

### ISSUE THREAD

**Issue by lfolco** [mage2tv/issues#18]
I often have a note taking app open while viewing videos, would be nice to be able to hide the nav bar in order to have the video be bigger.

**Comment by Vinai** [comment]
Thanks for the idea!
Just to confirm, I assume you mean the navbar on the left?
As a workaround, if you shrink the screen width to the breakpoint, it will be hidden automatically.

**Comment by lfolco** [comment]
Yes, the leftside navbar. I tried shrinking it, but then the text on the IDE becomes too small to see. Have you considered putting it in a popup / modal window that can be dragged around, independent of the other navigation? I could be an edge case with the note taking, of course.

**Comment by Vinai** [comment]
Yes, I certainly have thought about that. I'll won't have time to re-visit this issue before launch, but I'll surely will get back to it over time.

**Comment by lfolco** [comment]
Giving this a bump, hoping it's something you could revisit?

**Comment by Vinai** [comment]
@lfolco Absolutely, I haven't forgotten about this issue.
Currently I am torn between wanting to produce content and work on the website.
So far I've been prioritizing content production.
This week I'm making some changes under the hood to allow for increased content production.
I will get back to this topic in the not too far future!

**Comment by arnolds** [comment]
Bumping this as a nice to have. 

I watch Mage2tv side by side with my IDE open, and follow along the videos. And to get more space I'm hiding the filter menu through CSS in the dev tools. Which works good enough:

**CSS**

```
.video-page {
    left: 0;    
    padding: 0 20px;
    width: 100%;
    z-index: 100;
}
```

**Before**

![before](https://user-images.githubusercontent.com/9528895/59308265-85d8b400-8c98-11e9-9ad6-66b5bca73b27.png)

**After**

![after](https://user-images.githubusercontent.com/9528895/59308293-9852ed80-8c98-11e9-821e-b22d8a5d698b.png)

**Comment by lfolco** [comment]
Ooh that works! I normally just select the elements to hide what I don't need but this is much faster.

**Comment by Vinai** [comment]
Oh, veery nice! Thanks @arnolds!

**Comment by arnolds** [comment]
You're welcome! Keep up the great work @Vinai 👍

**Comment by Vinai** [comment]
I‘ve deployed a release that allows hiding the left navigation on desktop views.
Can you please check if that’s sufficient?
Thank you!

**Comment by lfolco** [comment]
Perfect, thanks!
