### ISSUE TITLE
Mark Video as Unwatched

### ISSUE THREAD

**Issue by osrecio** [mage2tv/issues#2]
When you have seen a video, there is the possibility to mark it as unseen, to see it later again or something like that

Thanks

**Comment by Vinai** [comment]
Great idea, thanks!
May I ask you a little further how you think that should work?

There currently are 3 places where the seen/unseen state of a video affects something:

1. the color in the video listing
2. the unviewed filter hides seen videos
3. the recently viewed videos dropdown

Selecting a video to be unwatched, would you think it should completely reset the video? Or should it still appear in the list of recently viewed videos?

In the meanwhile, as a workaround, maybe you can favorite the videos you want to watch again by clicking on the little star icon under the video player. Favorited videos can also be filtered in the listing.

**Comment by osrecio** [comment]
IMHO I think if you mark video as unseen, this video should be return to a initial state (reset video, actually). Disappearing from recently viewed videos, etc.

I think stars is a good idea, but maybe can you add a section like "See later". that you can mark a video to see later although the video is saw before or not.

PS: Great job behind mage2tv!!

**Comment by Vinai** [comment]
Thanks for your thoughts!

I already have a "playlists" (also sharable) feature planned, that could serve the purpose of "play later".

I'll add a "mark as unwatched" button or something to the video pages.
Would you also like to have a way to change a videos "seen" state from the listing page, or is that too much?

**Comment by Vinai** [comment]
Done and deployed.
On a video page, under the player for viewed videos, there now is a link to mark it as unseen again.

If you think the ability to mark videos as unseen from the listing page is important, please reopen this issue.
