### ISSUE TITLE
Hangs when your session expires

### ISSUE THREAD

**Issue by lfolco** [mage2tv/issues#20]
I tried to load a video after my session timed out, and I got the error "You must be logged in to continue" (or something along those lines), but then it just shows the loading:

![image](https://user-images.githubusercontent.com/1709329/36540453-7b6861ac-17a8-11e8-87cb-d495ce419d52.png)

But my account dropdown behaves as if I'm still logged in:

![image](https://user-images.githubusercontent.com/1709329/36540488-9172d874-17a8-11e8-98ed-1070ba39a988.png)

Requires a page refresh to get things back to normal.

**Comment by Vinai** [comment]
Interesting. The session timeout on the client side is 3 weeks, but maybe the server restarted - that causes all sessions to get lost. Thanks for the report. I'll look into persisting sessions on the server.

**Comment by lfolco** [comment]
It's happened a few times in the last few days.

**Comment by Vinai** [comment]
Are you maybe switching devices or browsers?
The app only allows one active login per account.

**Comment by lfolco** [comment]
Nope, was using chrome the whole time.

**Comment by Vinai** [comment]
Okay, thanks for the info. I'll have to do two things:
1. automatically update the logged-in status when the session expires.
2. figure out why the session is expiring.

I assume when this issue occurs one of the Ajax requests on the page returned a 403 response. If you get a chance, maybe you could check that is what is happening?

**Comment by lfolco** [comment]
Got it today:

![image](https://user-images.githubusercontent.com/1709329/36749271-e5916ca2-1bbf-11e8-8e32-cb6d48551f2e.png)

![image](https://user-images.githubusercontent.com/1709329/36749182-9e9e3dd4-1bbf-11e8-966a-90c9f87b1a1d.png)

I accidentally closed the console before I could inspect further.  I'll see if I can get it to happen again and will add more info.

**Comment by Vinai** [comment]
Ohh, interesting! It's the vimeo scripts giving a 403! How is that happening.
Any further information you can gather might be helpful. Much appreciated!

**Comment by lfolco** [comment]
I haven't been able to reproduce this in the last few days; I've used the same steps that I used before but no issues.

**Comment by Vinai** [comment]
Thanks for the update, I guess that's... good?

I'll leave this issue open for now, in case it happens again I would appreciate any information you can provide!

**Comment by Vinai** [comment]
Closing, especially since I extended the session timeout to 21 days with the latest release.
Should you encounter the problem again, please do reopen this issue again.
