### ISSUE TITLE
Indicate Sections/Topics 'Seen'

### ISSUE THREAD

**Issue by davidalexander** [mage2tv/issues#23]
Currently, the yellow 'seen' text and yellow camera icon indicate clearly which videos have been watched.

When coming to the listing after a while it is not initially clear which sections have been watched and the user needs to toggle each open to reveal this.

It would be nice if the section was highlighted/marked in some way so as to indicate it has been completely watched.

![colorsnapper_and_modifying_an_existing_table_-_mage2_tv](https://user-images.githubusercontent.com/55093/39960726-c2612598-561f-11e8-9bd9-265d4ca1eee4.jpg)

**Comment by Vinai** [comment]
Hi David,

thanks for the feedback, that is a great idea!

**Comment by Vinai** [comment]
In the meantime, as a workaround, you can click the `unviewed` tag in the left filter navigation, that will hide all videos that you already have seen. Maybe that already helps a bit.

**Comment by davidalexander** [comment]
Thanks. That’s a good tip!

**Comment by Vinai** [comment]
I've implemented your suggestion and deployed (sorry, you will have lost your user session if you currently where using the site because of the deployment).
After you log in again categories that contain only seen videos will now have the label "all seen".

**Comment by sprankhub** [comment]
This does not seem to work any more. Could you please double check @Vinai?

**Comment by sprankhub** [comment]
Sorry for that, it works indeed. However, it is a bit hard to spot, because the "all seen" is not highlighted in yellow. I suggest to highlight it in yellow as well.

**Comment by Vinai** [comment]
Great idea @sprankhub, will do!

**Comment by Vinai** [comment]
@sprankhub deployed.
