### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by zaheerbadi** [mage2tv/issues#24]
The issue is in Chrome.

When trying to log in and try to console it shows error like.
![image](https://user-images.githubusercontent.com/9264676/40069381-c134c042-5888-11e8-9c4a-b9d3eacc58cb.png)

**Comment by Vinai** [comment]
Thanks for your report - I'm looking into this and hope to have resolved it soon!

**Comment by Vinai** [comment]
The test payment provider contained a bug that led to invalid data stored in the db. The code is fixed now, so it won't happen again, but I still have to do something to fix the invalid data associated with your account, so you are able to log in again.

**Comment by zaheerbadi** [comment]
Thanks @Vinai

**Comment by Vinai** [comment]
You should be able to log in now. Please let me know if the issue still exists.

**Comment by zaheerbadi** [comment]
yes i can now login
