### ISSUE TITLE
Subscription process isn't compliant to german law

### ISSUE THREAD

**Issue by riconeitzel** [mage2tv/issues#26]
<img width="1129" alt="screen shot 2018-05-18 at 14 31 43" src="https://user-images.githubusercontent.com/930706/40234732-51ceedc8-5aa8-11e8-8417-7a8b70682119.png">

1. The final overview needs a specification of the subscription's content
2. Tax overview is missing (needs to be calculated from the total)
1. Overview is missing billing information
3. The Button needs to be called something like "order with obligation to pay" or "Jetzt zahlungspflichtig kaufen"
4. There's no Privacy Information (might already be accepted with sign up?!)
5. There's no Terms Conditions (might already be accepted with sign up?!)
6. There's no withdrawal information

**Comment by Vinai** [comment]
Thanks for the letting me know!

**Comment by Vinai** [comment]
All fixed! Thanks again 👍
