### ISSUE TITLE
Button sticks out of the right side of the containing element

### ISSUE THREAD

**Issue by riconeitzel** [mage2tv/issues#27]
<img width="1058" alt="screen shot 2018-05-18 at 14 31 49" src="https://user-images.githubusercontent.com/930706/40235023-265588ea-5aa9-11e8-885f-d16af73b4b43.png">

on subscription confirmation step 5

**Comment by Vinai** [comment]
Thanks for reporting the issue!

**Comment by Vinai** [comment]
This has been fixed in the meantime, but I had forgotten to close the issue. Thanks again for reporting!
