### ISSUE TITLE
Finding new content

### ISSUE THREAD

**Issue by alanablett** [mage2tv/issues#28]
You just published that two new videos had been added. It was difficult to see in the content where they were. It'd be handy to perhaps have a couple of additions.

1 - An entirely new section in the content area that lists videos sorted by when they were published. Latest videos at the top so everyone can see new content easily.
2 - Add "published at" date to the current video listings pages.

Keep up the great work @Vinai

**Comment by Vinai** [comment]
Thanks, very good ideas, I'll definitely do that!

As a short term fix, I'll post direct links to new videos that I add to existing sections.
Also, in case you already watched all the others, the `unviewed` filter in the left panel will hide all videos you already have seen.

Today I published these two:
[ES5 Pseudo Template Strings](https://www.mage2.tv/content/javascript/frontend-ui-components/javascript-uicomponent-es5-pseudo-template-strings/)
[Configuring UiComponents with Layout XML](https://www.mage2.tv/content/javascript/frontend-ui-components/configuring-uicomponents-with-layout-xml/)

**Comment by alanablett** [comment]
Just one more from me :)

When I am viewing a video it'd be great to have an idea of what category/section i'm in. Some links/breadcrumbs to "JavaScript UiComponents/Frontend UiComponents" for example when I am watching something in that category. I found that navigating with the next/prev navigated me through the sections effortlessly, but almost unknowingly too.

Thanks again

**Comment by Vinai** [comment]
I've implemented the "sort by date" feature and will deploy it with the next batch of videos tomorrow or Monday. 
When the videos are sorted by date, the publishing date is visible behind each video title.
Together with the "unviewed" tag filter it's actually more useful than I thought it would be. Thanks for the issue one again.

I'll keep this issue open until it's deployed.

Regarding seeing the current category, I'll work on that in the scope of https://github.com/mage2tv/issues/issues/19

**Comment by Vinai** [comment]
Deployed to production together with the new video batch.
