### ISSUE TITLE
Filtering gives black screen when viewing a video

### ISSUE THREAD

**Issue by mmmols** [mage2tv/issues#32]
When watching a video and trying to use the filters, it results in a black screen and it continues to be black even though I go back to another url in the browser (chrome 67.0.3396.99).

I guess another issue could be, if it really is nescascary to have a filtering options, when there's no lists of videos anywhere when viewing one. 

The issue happened  [here](https://www.mage2.tv/content/setup-scripts/managing-changes-over-time/managing-changes-over-time/)

![image](https://user-images.githubusercontent.com/18280977/42062372-b03f9632-7b2d-11e8-9d61-a3aaf2800412.png)

**Comment by Vinai** [comment]
Thanks for the report, good catch!

**Comment by Vinai** [comment]
Fixed and deployed 👍  Thanks for your help
