### ISSUE TITLE
When video is finished it exits the fullscreen mode

### ISSUE THREAD

**Issue by mmmols** [mage2tv/issues#33]
There's an issue when watching in fullscreen mode, and due to the short length of each video it happens quite often the video reloads when it finishes and gets the new one. This exits the fullscreen mode and it becomes tedious to navigate to the icon to make it fullscreen again.

**Comment by Vinai** [comment]
Thanks for the report! I agree, that isn't a pleasant experience.
As a short term fix I'll try to track fullscreen mode and have the new video request fullscreen again after reload. I'm sure this will not work reliably on all browsers though, but I should be able to add it quickly. Hope it helps in your case!
The long term fix would be to change the video in the vimeo player only if autoplay is enabled, and re-render the page when fullscreen is exited.
This is more complex to implement, so I'll do that as a second step.
Thanks again for reporting!

**Comment by Vinai** [comment]
After implementing the short term fix, I went ahead and implemented proper in-player video switching.
The changes are being deployed as I'm writing this.
I hope this will be a more pleasant ux now. Can you please let me know if this works for you?
Thank you!

**Comment by mmmols** [comment]
Works beautifully Vinai!

Thanks for the quick response to the issue and watching is so much more pleasant and smooth now! Yay!
