### ISSUE TITLE
Next subscription date wrong when subscribing

### ISSUE THREAD

**Issue by lfolco** [mage2tv/issues#38]
When you subscribe, right before clicking _Purchase_, it shows the next subscription date. For a three-month subscription, I got this:

![mage2tv-billing-interval](https://user-images.githubusercontent.com/1709329/46250316-0a82eb00-c406-11e8-8fb1-7d83449ca912.png)

The date should have been December 29, 2018.

**Comment by Vinai** [comment]
Thank you for opening the issue. I've tried to reproduce the issue, but so far no luck. I need to import a dump of the events from the production DB locally, and try to figure out what caused the issue for you.

**Comment by Vinai** [comment]
Finally fixed this bug. Will deploy with the next release. Thanks again for reporting it!
