### ISSUE TITLE
Content problem found

### ISSUE THREAD

**Issue by akashlal139** [mage2tv/issues#39]
In the following URL: 

https://www.mage2.tv/content/full-page-cache/overview/full-page-caching-concepts/

seems like there is some content problem in the following words:

If you are new to the topic of need a refresher, this is for you.

Please check and correct.

**Comment by Vinai** [comment]
Hi @akashlal139,
thanks for reporting the issue! We have fixed the typo in the release today.
Please keep reports coming, it's very valuable to us!
