### ISSUE TITLE
Add category to video list, when it's sorted bay date

### ISSUE THREAD

**Issue by Stepa4man** [mage2tv/issues#40]
![image](https://user-images.githubusercontent.com/15912461/46573870-8ac7c400-c9a3-11e8-9e8d-8f3aeedc742b.png)
Please add the category which video related too at the sorted by date list. Thanks!

PS I mean just name of category at the end of video name in list, not grouping it by categories as it's at initial content view page

**Comment by Vinai** [comment]
Thanks for the issue @Stepa4man!

**Comment by Vinai** [comment]
Just deploying a release that adds the category names to the listing page when the videos are sorted by date.
Thanks again for the suggestion!
