### ISSUE TITLE
Ability to make videos "unseen" from listing view

### ISSUE THREAD

**Issue by Stepa4man** [mage2tv/issues#41]
![image](https://user-images.githubusercontent.com/15912461/46582482-3e868d80-ca50-11e8-858e-26d1355777e9.png)

Please add an opportunity to make video "unseen" directly from video's list, without the necessity to go to every view-video page and do it there. 
Just make "seen" word as a btn which will manage changing of the status.

And perhaps the other way round

Thanks in advance.

**Comment by Vinai** [comment]
Good idea, thanks!

**Comment by Vinai** [comment]
Implemented. Clicking on "seen" will now mark the video as unseen.
