### ISSUE TITLE
Increase session timeout

### ISSUE THREAD

**Issue by albertnel** [mage2tv/issues#42]
I keep a mage2tv tab open because I sporadically view videos as I need it throughout the day,  but I first have to log in again every time due to an expired session. I find it extremely cumbersome to have to log in every hour or so. Please increase session timeout.

Tested in Firefox 62.0.3 (64-bit)

**Comment by Vinai** [comment]
Thank you for opening the issue! Will fix this!

**Comment by Vinai** [comment]
An update is being deployed right now that should fix the issue.

After this deployment the session timeout is set to 21 days, and also I changed to a persistent session storage so the session will survive application reboots (e.g. during deployments).
Please let me know if you have further issues around this topic.

**Comment by sprankhub** [comment]
Hmm even though the cookie lifetime looks okay to me, I have to re-login every day. I watched a video yesterday at 6pm and had to re-login now. Any idea @Vinai?

**Comment by Vinai** [comment]
Hm, I think heroku reboots the instance once a day, maybe not always, but I do see a reboot in the logs (that I didn't trigger).
In theory the persistent session storage should be enough for sessions to survive a app reboot, but to be honest - I haven't tested that.
I'll have to see if I can replicate that behavior locally.

**Comment by sprankhub** [comment]
Bump :)

**Comment by Vinai** [comment]
I’ve done some work on the session storage. It would be great if you could let me know if you still experience the premature session timeouts.

**Comment by sprankhub** [comment]
Thanks Vinai! I logged in yesterday and my session is still valid today. So at least it is better than before :-)

**Comment by albertnel** [comment]
Nice, looking good from my side as well, thanks Vinai! :)

**Comment by Vinai** [comment]
Awesome, thank you both very much for checking and giving feedback!

In the new system sessions persist over container restarts and also deployments, so hopefully this will provide a better user experience.
