### ISSUE TITLE
Wrong video for Adding a custom EAV attribute to an attribute set

### ISSUE THREAD

**Issue by peterjaap** [mage2tv/issues#43]
The video on https://www.mage2.tv/content/setup-scripts/adding-a-custom-eav-attribute/adding-a-custom-eav-attribute-to-an-attribute-set/ talks about the PropertyMapper for the product eav attribute, not about adding an eav attribute to an attribute set.

**Comment by peterjaap** [comment]
After clearing the localstorage and hitting hard-refresh, the correct video does appear. So not a mistake, but a bug of some kind.

**Comment by peterjaap** [comment]
Can't seem to reproduce consistently. Closing for now.

**Comment by Vinai** [comment]
Thanks for the report. This issue seems to crop up once in a while, but I also haven't been able to reproduce it.
I've got an open ticket to add a button that clears local storage to make solving it a bit easier.
