### ISSUE TITLE
Autoplay next video doesn't work

### ISSUE THREAD

**Issue by Stepa4man** [mage2tv/issues#46]
#### Description
After playing current video, player switched to the next one, but doesn't start play it.
The only spinner spins:
![image](https://user-images.githubusercontent.com/15912461/50481809-40774180-09ec-11e9-8857-a3dea9093893.png)

#### ENV
OS: Linux Ubuntu
Browser: Google Chrome
Version: 71.0.3578.98 (Official Build) (64-bit)

#### Steps to reproduce
1. Go to any video page
2. Switch on autoplay
3. Watch or scroll video till the end

#### Expected result
1. Next vidoe displayed
2. It starts play automatically

#### Actual result
1. Next video displayed
2. Spinner in front of video started to spin
3. Nothing happened

**Comment by Vinai** [comment]
Thanks for the issue @Stepa4man! The vimeo player JavaScript API is a bit unstable it seems.
Does this always happen for you?
Does it make a difference if you clear local storage and force reload the page?

**Comment by Stepa4man** [comment]
Hey @Vinai! Happy New year!

It happens all the time at Chrome, FireFox. Even if I clear local storage for both mage2.tv and vimeo.
![image](https://user-images.githubusercontent.com/15912461/50590093-25944980-0e92-11e9-9791-329ef0119486.png)

**Comment by Vinai** [comment]
Hi, thanks for reporting your issue.
Unfortunately I still can't reproduce the issue on OS X.
On some mobile devices (iPads and iPhones) playing video in a browser without user interaction has unfortunately been disabled by Apple.

With chrome browser (regardless on which platform) the autoplay behavior is based on previous interactions with the website. That is, if you have started videos recently a few times explicitly, chrome will allow autoplay to work.
I've read reports of similar behavior on Safari, too.

In Firefox it should work. I do not know about Operas behavior in regards to video autoplay. 

But just in case it helps, I have added a button to refresh the application state on the bottom of the [Account Profile page](https://www.mage2.tv/account/profile).

![Bildschirmfoto 2019-04-15 um 16 00 29](https://user-images.githubusercontent.com/72463/56138684-a4bc1200-5f97-11e9-9b1c-9fb3f3f5b939.png)

This at least should help in cases where a video doesn't properly progress to the correct next video after an update to the website.

**Comment by Vinai** [comment]
Closed, mainly because I haven't heard this issue in a long time.
