### ISSUE TITLE
Magento U on-demand subscription access to Mage2.tv

### ISSUE THREAD

**Issue by AMP69** [mage2tv/issues#48]
The details on the Magento site for '[MAGENTO U ON-DEMAND SUBSCRIPTION](https://u.magento.com/magento-u-on-demand-subscription)' state that 12 months access to Mage2.tv will be supplied.

How is this access achieved? Logging in with the same details as registered with Magento U does not provide access.

**Comment by Vinai** [comment]
Magento U provides their customers with a coupon code and instructions how to activate the Mage2 TV subscriptions.
Currently they have to send the desired user name, email and the coupon code to contact@mage2.tv.
Then the account will be created, and they will be able to authenticate either with github (in case the same email is associated with a github account), or by using the reset password link to give themselves a password.

In a couple of weeks the process will be automated. Then it will be possible to supply the coupon code during registration.
