### ISSUE TITLE
FULL PAGE CACHE DEBUGGING HEADERS IN DEVELOPER MODE video is same as Full page cache overview 

### ISSUE THREAD

**Issue by avattam06** [mage2tv/issues#49]
The FULL PAGE CACHE DEBUGGING HEADERS IN DEVELOPER MODE video is same as Full page cache overview. Can you please update it?

Thanks!!

**Comment by Vinai** [comment]
Hi @avattam06, I can't reproduce the problem, probably the state of the application got inconsistent.
Please try force-reloading the page https://www.mage2.tv/content/full-page-cache/overview/full-page-cache-debugging-headers-in-developer-mode/ 

If that doesn't help, please log out, clear the browser local storage for website, and log in again.
Now the video should work as expected.

Please let me know if this helped.
Sorry for the inconvenience!

**Comment by Vinai** [comment]
Where you able to see the correct video?

**Comment by avattam06** [comment]
Yes, I am able to view the correct video.

Thanks!

**Comment by Vinai** [comment]
Thanks for the update!
