### ISSUE TITLE
"Suprising" position of "application reset" (i.e. home button)

### ISSUE THREAD

**Issue by andrewhowdencom** [mage2tv/issues#5]
I was looking for it in top left but found it in top right. Not problematic, but I only get to be surprised a couple times before i get used to using it. 

(https://en.wikipedia.org/wiki/Principle_of_least_astonishment)

**Comment by Vinai** [comment]
Hey Andrew!
Thanks, good point.
I was struggling where to place that action.

Currently it's the clicking on the logo in the top right where you found it, or in the profile dropdown.
It's also possible to get back to the listing page using the search...

Do you happen to have a good idea by chance? :)

**Comment by andrewhowdencom** [comment]
So, I went looking at the material.io guidelines -- the closet thing I can come up with is the "App bar": 

https://material.io/guidelines/layout/structure.html#structure-app-bar

In this case, it would be smth having only the logo on the left, and all buttons on the top right. I think it's important to note, though -- my "astonishment" is moderated by the fact I spend a lot of time in Google properties, who almost universally adopt this design.

I'm not sure how you'd collect data on this; maybe A/B test and check usage rates? Unsure.

Caveat: I only know material.io as a UX framework, I've never bothered looking further. There are better people than me at this at this lol

**Comment by Vinai** [comment]
Still needs styling, then all pages (except the content list) will have a "content" icon and button in the top right corner beside the account menu.
Hope that makes it easier to navigate. Thumb-navigation on mobile works. Will leave this issue open until it is deployed.

**Comment by Vinai** [comment]
Deployed.
