### ISSUE TITLE
feedback to magetv

### ISSUE THREAD

**Issue by gihovani** [mage2tv/issues#51]
hi, first thank you for share your knowledge, with the magento community.
Your video series helps me a lot to know how the magento works, because some features i was imagine the magento makes magic. Now i understand i litle bit how magento works, thank you so much.

I found a litle mistake some times happening here, the autoplay button doesnt works, and some times play the same or previous video.

One more time thank you to give your time to us (beginers in magento).

**Comment by gihovani** [comment]
the same issue already open #46

**Comment by Vinai** [comment]
Hi @gihovani, thank you for your issue report!
The issue #46 is actually only related to the autoplay feature, but you also mentioned sometimes the same or a previous video is played.

If that happens, please try to reset the application state with the button at the bottom of the [account profile page](https://www.mage2.tv/account/profile).
That will reload the video catalog from the server and should take care of those glitches.

Thanks again, Vinai
