### ISSUE TITLE
activate cache-clean.js hotkeys in php storm

### ISSUE THREAD

**Issue by mahmoud-ismail** [mage2tv/issues#52]
Hi Vinai,

I have installed cache-clean js tool globally and add it on PhpStorm startup as a node js project with the parameter -w, also I have installed node js version 10.15.3 .

the next step to make the hotkeys working is open the registry and check nodejs.console, but the problem is, I don't found it in the registry to check it, and still the hotkeys are disabled.

the second issue is when I try to run the cache-clean js tool from the command :

 ~/.composer/vendor/bin/cache-clean.js -w

the watcher doesn't work automatically with each change, I have to click on the terminal first then the tool flushing the specific segment.
is that normal or not? because I see it working with you automatically without any clicking on the terminal.

Regards,

**Comment by Vinai** [comment]
What version of Magento are you using?
What version of PHPStorm are you using?
What operating system are you using?
If you have cache related configuration in `app/etc/env.php`, can you please post that here, too?

**Comment by Vinai** [comment]
Also, just for reference, maybe you can check the issues at https://github.com/mage2tv/magento-cache-clean/issues in case there is some helpful information already.

**Comment by mahmoud-ismail** [comment]
Hi vinai,
I have answered your question with a new ticket in the mentioned link.
thank you,

**Comment by Vinai** [comment]
Okay, cool, then lets continue the thread there, and I'll close this issue.
