### ISSUE TITLE
Magento Components Image from OVERRIDING INTERFACE PREFERENCES IN DI.XML

### ISSUE THREAD

**Issue by JamesFX2** [mage2tv/issues#57]
I searched for a readable version of this image. 

![image](https://user-images.githubusercontent.com/8654869/68475347-cf193980-021f-11ea-96af-f6c0d4991a42.png)

Is it available anywhere?

**Comment by Vinai** [comment]
The image is linked from this document:
https://github.com/magento/architecture/blob/master/design-documents/service-isolation.md

This is the direct link to the image in the repo:
https://github.com/magento/architecture/blob/master/design-documents/service-isolation/magento-services.png

**Comment by Vinai** [comment]
PS: I've also added a link the the diagram in the comments.
