### ISSUE TITLE
Incorrect video attached for WELCOME TO THE JAVASCRIPT AND UICOMPONENT SECTION

### ISSUE THREAD

**Issue by sajidpatel** [mage2tv/issues#58]
The video for WELCOME TO THE JAVASCRIPT AND UICOMPONENT SECTION
is actually the video from UNINSTALL SCRIPTS.

**Comment by sajidpatel** [comment]
I have tried to load the video again and the correct video now loads.  False-positive!

**Comment by Vinai** [comment]
Thanks for the update!
