### ISSUE TITLE
Video controls hidden behind footer @ full screen

### ISSUE THREAD

**Issue by ennostuurman** [mage2tv/issues#6]
Video controls are hidden behind fixed footer at full screen, see screenshot.

![mage2tv-beta-missing-video-controls](https://user-images.githubusercontent.com/1906257/34867819-d5f47abc-f781-11e7-8921-9d40b72f0c5f.png)

**Comment by Vinai** [comment]
Uh, good find! Thanks!

**Comment by Vinai** [comment]
Which browser are you using? Could you give me a little more information maybe?
I'm trying to get into the same state, but no luck so far.
I've tried with Chrome and Firefox in Full-Screen mode, but without a full-screen video player.
Maybe I need to change the screen resolution for this to happen?

**Comment by ennostuurman** [comment]
@Vinai that was both in Chrome and Firefox on Windows 10 .

Ubuntu however does show the video controls in both Firefox and Chrome however there the additional info is hidden behind the fixed footer in full screen mode where the page can not be scrolled. See attached screenshots.

![mage2tv-beta-footer-comments-behind-fixed-footer-full-screen](https://user-images.githubusercontent.com/1906257/34870892-cf0eb190-f78b-11e7-8c1e-7ffa1a03a862.png)
![mage2tv-beta-footer-comments-behind-fixed-footer-not-full-screen](https://user-images.githubusercontent.com/1906257/34870893-cf2de628-f78b-11e7-9518-ba32fd4fe6ec.png)

**Comment by Vinai** [comment]
Thanks for that additional info!
If the page where scrollable, that should fix it, correct?

**Comment by ennostuurman** [comment]
yes, looks like changing the overflow-y from scroll to auto on the body and main element should fix this

**Comment by Vinai** [comment]
Hi @ennostuurman,
even though we where not able to reproduce the issue, I deployed a potential fix.
Could you please try again and let me know if the issue still exists?
Thank you very much in advance!

**Comment by ennostuurman** [comment]
Hi @Vinai ,
just subscribed and watching the KO view model video right now => I can confirm the issue is fixed ;-)

**Comment by Vinai** [comment]
Thanks! If you are watching videos right now I'll refrain from doing a deploy now so you don't loose your session :)

**Comment by ennostuurman** [comment]
@Vinai but why planning a deploy during business hours (EST)  ;-) ?  I will ping you when I've finished - already very informative, so thx!

**Comment by Vinai** [comment]
Happy to hear it! I tend to do a deployment every time I finish a feature / bug fix :)
This time I fixed autoplay on chrome.

**Comment by ennostuurman** [comment]
@Vinai I call it a day !
