### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by swiftotter-david** [mage2tv/issues#60]
I'm trying to login via Chrome using email/password, but the server returns a 500 error.

<img width="1680" alt="Screen Shot 2020-05-12 at 10 11 04 PM" src="https://user-images.githubusercontent.com/56172988/81770488-a52a2380-949d-11ea-8f6b-f5e8380b1f83.png">

**Comment by Vinai** [comment]
Hi @swiftotter-david, sorry for the inconvenience!
Thank you for opening the issue. I've fixed the problem and you should be able to log in again now!

Kind regards,
Vinai

**Comment by swiftotter-david** [comment]
@Vinai No worries! Thanks, I'm able to log back in. And thanks for putting together such a great resource!
